eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9000
spring:
  application:
    name: service-turbine
security: 
  basic: 
    enabled: false
turbine:
  aggregator:
    clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: service-feign,service-ribbon  ### 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")