eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
    sleuth: 
      enabled: true
      sampler:
        percentage: 1
  zipkin: 
   base-url: http://localhost:9411